export const GET_REPOSITORIES = 'GET_REPOSITORIES';
export const STORE_REPOSITORIES = 'STORE_REPOSITORIES';
export const LOADING_FAILED = 'LOADING_REPOSITORIES_FAILED';
export const SAVE_REPOSITORIES_RENEW_ID = 'SAVE_REPOSITORIES_RENEW_ID';